### ISSUE TITLE
Bitwarden manager claims JSON file is invalid.

### ISSUE THREAD

**Issue by josemotanet** [roddhjav/pass-import#123]
It's possible that the parser is not up to date with a potential new schema. Please advise.

# Steps to reproduce

1. Export vault as `json` from Bitwarden;
2. Run `pass import bitwarden file.json`;
3. :boom: _Error: file.json is not a valid exported bitwarden file._

**Comment by josemotanet** [comment]
Running `-vvv` gave me this:

```
.  Trying to guess file format.
  .  Importer: bitwarden, Format: csv, Version:
  .  Importing passwords from BitwardenCSV to PasswordStore
  .  Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pass_import/__main__.py", line 329, in pass_import
    importer.parse()
  File "/usr/lib/python3.8/site-packages/pass_import/formats/csv.py", line 40, in parse
    raise FormatError()
pass_import.errors.FormatError
```

**Comment by roddhjav** [comment]
Can you ensure your exported json is in the same format [than this reference test file](https://github.com/roddhjav/pass-import/blob/master/tests/assets/db/bitwarden.json). The format of this file seems up to date with the current Bitwarden export format.

**Comment by josemotanet** [comment]
The schema appears to comply from my side, yes.
To be clear: I exported my own vault just about now.

Although I'm not anywhere versed in Python, I tried to dig into the tests and see if I could find anything. I noticed there were some failing tests but I don't think any one of those had to do with Bitwarden specifically.

**Comment by roddhjav** [comment]
Can you clone the dev branch I pushed and test it with: 
```
pass import BitwardenJSON file.json -vvv
```

This way, you will bypass the format detection and enforce the use of the import class you want to use.

**Comment by josemotanet** [comment]
I have cloned the `dev` branch. The error above is bypassed.

This time, my hurdle is as follows:

```
[x] Error: invalid credentials, password encryption/decryption aborted.
```

If I'm reading the code correctly, I can't seem to find a reason that satisfies the following conundrum. How does the exception rise if `isvalid()` is hardwired to `True`?

https://github.com/roddhjav/pass-import/blob/0cea50998d7a9091fef62a03d2a29f6aea67e347/pass_import/core.py#L111-L117

Please advise. Thank you @roddhjav.

**Comment by roddhjav** [comment]
This is something else. Before importing password in your password repository, pass-import ensures your gpg keyring is usable for this repository. You need to ensure that:
- All the public gpgids are present in the keyring.
- All the public gpgids are trusted enough.
- At least one private key is present in the keyring.

So the issue is usually because one of your gpg key is not trusted enough.

**Comment by josemotanet** [comment]
I can confirm this. Will look further into it and report back.

**Comment by josemotanet** [comment]
I have reset my password store and tried again. The result was successful; thank you.

I trust that you'll be able to understand the issue with detecting the right manager. If I had any reasonable understanding in Python and the tests that would cover this issue, I would happily submit a PR. Alas, I believe I would be unfruitful.

**Comment by spurgelaurels** [comment]
Having a similar issue (which I resolved while gathering evidence for this post :D )

Exported JSON from Bitwarden, and tried to import to pass. Same error, and -vvv showed pass is trying to import with CSV. 
So I re-exported with CSV. 

```
  .  Trying to guess file format.
  .  Importer: bitwarden, Format: csv, Version:
  .  Importing passwords from BitwardenCSV to PasswordStore
  .  Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pass_import/__main__.py", line 338, in pass_import
    importer.parse()
  File "/usr/lib/python3.9/site-packages/pass_import/formats/csv.py", line 40, in parse
    raise FormatError()
pass_import.errors.FormatError


 [x] Error: bitwarden_org_export_20210417105350.csv is not a valid exported bitwarden file.
```

This might make sense, as the CSV being exported by Bitwarden is `collections,type,name,notes,fields,login_uri,login_username,login_password,login_totp` which doesn't match https://github.com/roddhjav/pass-import/blob/master/tests/assets/db/bitwarden.csv


Checked the JSON format against the JSON example, and I do see a bit of a difference. `collections` instead of `folders`, and an additional encryption config. Other than that, the file looks mostly fine. 

I removed the encryption line, and changed `collections` to `folders` and it seemed to import. 

```
{
  "encrypted": false,
  "collections": [
    {
      "id": "<redacted>",
      "organizationId": "<redacted>",
      "name": "Personal",
      "externalId": null
    },
```


So it looks like the

**Comment by stev-kast** [comment]
I just had the same problem and want to write how I solved it:

@roddhjav mentions that every gpgid must be in the keyring, these ids are in .password-store and the id I used to set up pass was my email address as they instruct in the docs, so I just left one gpg key in my system and added my personal information to it based on [this](https://docs.github.com/en/authentication/managing-commit-signature-verification/associating-an-email-with-your-gpg-key), now the key has my email address and I could import the passwords. 

I know this may be something dumb but I hope this helps someone.
