### ISSUE TITLE
Save Login Names as “Username”

### ISSUE THREAD

**Issue by baums** [roddhjav/pass-import#135]
The preferred organizational scheme of pass (https://www.passwordstore.org/) prefixes login names with “Username”:

    Username: me@example.com

rather than “login”:

    login: me@example.com

(as does pass-import, at least from CSV format). As a consequence, helm-pass’s (https://github.com/emacs-helm/helm-pass/) “Copy username to clipboard” fails with “Username not found!” Please use “Username.”

**Comment by baums** [comment]
Cf. this issue: https://github.com/emacs-helm/helm-pass/issues/7

**Comment by roddhjav** [comment]
By definition of the pass format, there is no such thing as a "preferred" organizational scheme. pass-import tries to respect the very broad password organization used by [browserpass](https://github.com/browserpass/browserpass-extension#organizing-password-store). This is why it uses `login`, because it is the first keyword, browserpass is locking for. Changing it would most likely break things. To respect this broad pass format, it is up to helm-pass to support other keywords than `Username`.

**Comment by baums** [comment]
Well, “preferred organzational scheme used by the author [of pass].” But I agree, emacs-helm should accept either.

**Comment by baums** [comment]
Actually, it seems browserpass (https://github.com/browserpass/browserpass-extension#organizing-password-store) would accept “Username” too:

    Username must be defined on a line starting with login:, username:, or user: (case-insensitive)
