### ISSUE TITLE
Reading from pipes

### ISSUE THREAD

**Issue by pkoch** [roddhjav/pass-import#174]
I'd like to add something like `bw --raw export --format json | pass import -fa bitwarden  -` to my cron.

However, it seems like pass-import always wants a file to read from, and not a pipe. Is this something you'd be open to get a PR for? Where's the right place to make this change, roughly?

**Comment by roddhjav** [comment]
This used to be a feature of pass-import, I removed it long time ago as it was causing issues for some pm (and because nobody was using it). The good news it that pass-import still has the logic to support it.

So PR are more than welcome. You should hack around the [`detectmanager`](https://github.com/roddhjav/pass-import/blob/fe05ceebf5dc171d5e5791c56bf0b52b0eecce44/pass_import/__main__.py#L284) function in the main file. The stdin file should go into `conf['in']`. Then it should somewhat work as this `conf['in']` is later given to the password manager class and used as file, see [here](https://github.com/roddhjav/pass-import/blob/fe05ceebf5dc171d5e5791c56bf0b52b0eecce44/pass_import/core.py#L83)

If you get an issue with format detection you can force it to use a given import class with  `pass import BitwardenJSON -`

**Note:** direct import using the `bw` cli is a planned feature (currently in test phase), so in the future you should be able to directly use something like `pass import bitwarden` to do the same thing.

**Comment by pkoch** [comment]
> This used to be a feature of pass-import, I removed it long time ago as it was causing issues for some pm (and because nobody was using it).

Can you perhaps point me to the ticket/PR for the problems you had that made you want to take this out? Ideally, I'd try to sidestep those.

> direct import using the bw cli is a planned feature (currently in test phase), so in the future you should be able to directly use something like pass import bitwarden to do the same thing.

Hmm, maybe I should concentrate on helping on this, then! Where can I join the fun?

**Comment by roddhjav** [comment]
I removed stdin in 6d2e2fb61b680e7cbba522a19813c0b363c107fd it was part of the dev branch (see #84). Now this was during the version 2 of the project, so many things changed since that it might be useless.

I will push the wip `bw` support on the dev branch once I get some time.

**Comment by pkoch** [comment]
I've since concentrated all my password on Bitwarden, and I've been happy enough using it.

But I'd be interested to know when your new `bw` code is in, and maybe our schedules/needs will align then.

**Comment by roddhjav** [comment]
You can now try [260c81f](https://github.com/roddhjav/pass-import/pull/175/commits/260c81f54d82d0d38602a303baf7c83f565262c6) from the dev branch. But please note, this is still in dev stage. I usually do not commit such code that is not fully tested in CI (it should still works fine for basic use), but as I do not have time to work on this these days, it seems fair to allow you to play with it anyway.

To try it, from the dev branch: `pass import -vvv bitwarden <bitwarden-email>`

**Comment by pkoch** [comment]
Thank you for sharing! 🙌

However, I'm at a point in my life where other obligations prevent playing with this from bubbling up in my priority stack.

I'll let you know if I happen to get a chance, tho!

**Comment by roddhjav** [comment]
For future me: this feature is currently not a priority.
