### ISSUE TITLE
release file issues with pandoc manuals

### ISSUE THREAD

**Issue by sthen** [roddhjav/pass-import#186]
Hi, there are some slight issues relating to the new pandoc-generated manpages in the various distributed tar.gz files.

The file on pypi (https://files.pythonhosted.org/packages/7a/06/286f31049a80ad256c6fe8478d405117f8cfdedb512f0d793d62ec0be404/pass-import-3.3.tar.gz) includes formatted share/man/man1/{pass-import,pimport}.1 files, which is helpful to reduce build dependencies (pandoc takes forever to build, and is only available on limited machine architectures), but misses share/__init__.py so the setup.py script fails, and doesn't include the tests directory (which is somewhat useful for distro packagers).

The github releases artefact (https://github.com/roddhjav/pass-import/releases/download/v3.3/pass-import-3.3.tar.gz) includes share/__init__.py (and tests) but no .1 files.

Would it be possible to either add preformatted files to the github tar.gz, or allow "from share import makedoc" / add enough files so the pypi tar.gz can be built please?

**Comment by roddhjav** [comment]
Hi, thanks for the report. I should ensure all doc generation is done during pip/deb package generation, not installation so that I can drop pandoc requirement.

`share/__init__.py` is an internal script. It does not aim to be shipped. I mean it is part of a git tallbar but not of a distribution package. Same for the tests.

I need to see how to run this pandoc generation on python dist build but not when someone it doing `pip install`. Help is welcome.

**Comment by roddhjav** [comment]
Should be fixed with pass-import 3.4
