### ISSUE TITLE
AttributeError: module 'pass_import' has no attribute '__version__'

### ISSUE THREAD

**Issue by nullomata** [roddhjav/pass-import#193]
I am trying to install `pass-import` on arch with python 3.11.1. I tried using Paru, but `Paru -S pass-import` returned the titular error 
```
AttributeError: module 'pass_import' has no attribute '__version__'
```
I tried to build it manually with `python setup.py install` but I get the same error. I played around with different python versions, and for any version =>3.10.6 I get the aforementioned error. With python versions <3.10.6 it fails to build but with a different error claiming a missing module. 

I'm using `asdf` to manage different python versions, and when building locally I am doing it inside of a virtual env with venv. 

Do you have any suggestions or ideas of what's going on here?

**Comment by roddhjav** [comment]
I wasn't able to reproduce this. The `__version__` variable [is imported by default](https://github.com/roddhjav/pass-import/blob/f1b622cc968e769e34542fd034ba32fee55a1a8c/pass_import/__init__.py#L17) and I don't see this changing in a in python update.

**Comment by g1y** [comment]
I was facing this issue as well, and never really go to the bottom of what was happening. It seemed to happen for all sorts of python versions (3.6, 3.8, 3.11) and all sorts of versions of setuptools as well.

Setuptools seems to be able to work okay if __version__ is set in __init__.py with a scalar since it goes down the path of [analyzing it statically first](https://github.com/pypa/setuptools/blob/v62.6.0/setuptools/config/expand.py#L189), then tries the broken module loading path. I don't feel like it's fair to suggest that as a fix, since it's probably just masking the problem.

Another interesting bit is that [setuptools just specifies a string for its version in its setup.cfg](https://github.com/pypa/setuptools/blob/6510d128c4068fbd6dc31f84ac3548d0bdbed027/setup.cfg#L3) and doesn't doesn't reference a module. 

Wish I could help more

**Comment by roddhjav** [comment]
Thanks @g1y I was able to confirm this to. For now I will simply use a string in `setup.cfg`.
