### ISSUE TITLE
Keepass: invalid password

### ISSUE THREAD

**Issue by thomas-mc-work** [roddhjav/pass-import#204]
Hello,

I've encountered a strange issue. I want to import from an existing Keepass-Database using this command:

    PASSWORD_STORE_DIR=$HOME/.local/share/gopass/stores/root pimport gopass keepassxc 'ecg.kdbx' 

The respone is:

    Password for ecg.kdbx: 
     [x] Error: invalid credentials, password encryption/decryption aborted.

I can open the file properly using KeePassXC (version `2.7.6` on Xubuntu 22.04.3) and the corresponding password. To verfiy the underlying library I wrote a small test application:

```python
from pykeepass import PyKeePass

kp = PyKeePass('ecg.kdbx', password='123456')
for group in kp.groups:
    print(f'{group.path}')
```

This is working fine and print all existing groups as expected.

Has anybody an idea what's going wrong here? Can you give me instructions to debug the situation further? Thanks!

**Comment by glasseyes** [comment]
And looking deeper it looks like it is failing in isvalid of the pass manager, so the problem is that it doesn't like the gpg key for some reason, so most likely a local issue rather than a problem with pass import.

**Comment by koalp** [comment]
Hello, 
I had the same issue because I did not trust the gpg key I used for my vault.
If you have the same issue, you can trust it using 
```
gpg --edit-key
trust
```

**Comment by Mikilio** [comment]
In my case, I received this error because pass was fine with the IDs from `gpg --list-keys`. However, this programs doesn't seem to like them because it relies on a command like this:
```
gpg --with-colons --batch --list-keys -- <id>
```
and the output of this with my provided ID for pass looked like this:
```
gpg: error reading key: No public key
```
And this apparently doesn't sit well with this program.

Now why exactly I get this error, I don't really want to talk about it, but the takeaway should be that to use this program you should use a `gpgid` in pass obtained by:
```
gpg --list-keys --keyid-format <SHORT or LONG>
```

These should be used without the algorithm's name, like cv25519, etc.

**Comment by thomas-mc-work** [comment]
Thank you very much for your replies! That has helped my to solve this issue. The trust level has to be set to `5 = I trust ultimately`
