### ISSUE TITLE
LastPass: ampersands are escaped and break the password

### ISSUE THREAD

**Issue by hrantzsch** [roddhjav/pass-import#35]
I imported my passwords from LastPass and all passwords that contained the character `&` in the original are broken. `foo&bar` is imported as `foo&amp;bar`.

Folder names have the same issue (but here it doesn't really hurt).

I checked some other special characters as well, but apparently the ampersand is the only one that breaks.

I used pass-import 2.1 (from AUR).

**Comment by roddhjav** [comment]
That's weird, because pass-import  is tested against all case of special characters. See https://github.com/roddhjav/pass-import/blob/master/tests/db/lastpass.csv line 6, ampersand is present, tested and checked.

Could you tell me if you lastpass export csv (that contains ampersands) is similar to this test file?

**Comment by hrantzsch** [comment]
Oh interesting! If I export the file via the LastPass website it has the same format as your test data and would probably work fine. If I export it from the chromium plugin though, ampersands are already escaped in the exported data.

So it's really no pass-import issue. More an issue of LastPass that their export function is inconsistent.

Thank you!
